name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "heightmaps" ] # TODO: remove 'heightmaps' after merge

jobs:
  build:
    name: Build
    uses: ./.github/workflows/cmake.yml
    with:
      build_type: Release
      run_tests: true
